from aws_cdk import (
    Stack,
    CfnOutput,
    RemovalPolicy,
    aws_s3 as s3,
    aws_s3_deployment as s3deploy,
    aws_cloudfront as cloudfront,
    aws_cloudfront_origins as origins,
)
from cdk_nag import NagSuppressions
from constructs import Construct


class FrontendStack(Stack):
    """Private S3 + CloudFront distribution for the frontend SPA."""

    def __init__(self, scope: Construct, construct_id: str, *, api_url: str = "", **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # Private S3 bucket — no public access
        site_bucket = s3.Bucket(
            self, "FrontendBucket",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        # CloudFront OAC → private S3
        distribution = cloudfront.Distribution(
            self, "FrontendCDN",
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3BucketOrigin.with_origin_access_control(site_bucket),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            ),
            default_root_object="index.html",
            error_responses=[
                cloudfront.ErrorResponse(
                    http_status=403,
                    response_http_status=200,
                    response_page_path="/index.html",
                ),
                cloudfront.ErrorResponse(
                    http_status=404,
                    response_http_status=200,
                    response_page_path="/index.html",
                ),
            ],
        )

        # Deploy frontend files + generated config to S3
        s3deploy.BucketDeployment(
            self, "DeployFrontend",
            sources=[
                s3deploy.Source.asset("frontend"),
                s3deploy.Source.data("config.js", f'window.__CONFIG__ = {{ API_BASE: "{api_url}" }};'),
            ],
            destination_bucket=site_bucket,
            distribution=distribution,
            distribution_paths=["/*"],
        )

        CfnOutput(self, "FrontendUrl", value=f"https://{distribution.distribution_domain_name}")

        NagSuppressions.add_stack_suppressions(self, [
            {"id": "AwsSolutions-CFR1", "reason": "Geo restrictions not required for this fashion ecommerce demo"},
            {"id": "AwsSolutions-CFR2", "reason": "WAF not required for static frontend demo deployment"},
            {"id": "AwsSolutions-CFR3", "reason": "Access logging not required for demo — CloudFront standard logs available via console"},
            {"id": "AwsSolutions-CFR4", "reason": "Using default CloudFront TLS certificate which enforces TLSv1.2"},
            {"id": "AwsSolutions-S1", "reason": "Access logs not needed for frontend static asset bucket — CloudFront logs provide request visibility"},
            {"id": "AwsSolutions-IAM4", "reason": "AWS managed policies used by CDK BucketDeployment custom resource"},
            {"id": "AwsSolutions-IAM5", "reason": "Wildcard permissions generated by CDK BucketDeployment for S3 object operations and CloudFront invalidation"},
            {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK BucketDeployment custom resource"},
        ])
